[tool.poetry]
name = "xcashu"
version = "0.1.0"
description = ""
authors = ["callebtc callebtc@protonmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cashu = "^0.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
